name: Simple manual workflow - Three Env

on:
  workflow_dispatch:
  push:
    branches:
      - Dev

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    env:
      AZURE_WEBAPP_NAME: Test-App-Dev
      AZURE_WEBAPP_PACKAGE_PATH: "./publish"

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Step 3: Restore dependencies
      - name: Restore
        run: dotnet restore ./WebApp/WebApp.sln

      # Step 4: Build project
      - name: Build
        run: dotnet build ./WebApp/WebApp.sln --configuration Release --no-restore

      # Step 5: Publish project
      - name: Publish
        run: dotnet publish ./WebApp/WebApp.sln --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Step 6: Deployment
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.TESTAPPDEV }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
		  
	QA:
    runs-on: ubuntu-latest
    environment: QA
	needs: DEV

    env:
      AZURE_WEBAPP_NAME: Test-App-QA
      AZURE_WEBAPP_PACKAGE_PATH: "./publish"

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Step 3: Restore dependencies
      - name: Restore
        run: dotnet restore ./WebApp/WebApp.sln

      # Step 4: Build project
      - name: Build
        run: dotnet build ./WebApp/WebApp.sln --configuration Release --no-restore

      # Step 5: Publish project
      - name: Publish
        run: dotnet publish ./WebApp/WebApp.sln --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Step 6: Deployment
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.TESTAPPQA }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
		  
	PROD:
    runs-on: ubuntu-latest
    environment: PROD
	needs: QA

    env:
      AZURE_WEBAPP_NAME: Test-App-Prod
      AZURE_WEBAPP_PACKAGE_PATH: "./publish"

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Step 3: Restore dependencies
      - name: Restore
        run: dotnet restore ./WebApp/WebApp.sln

      # Step 4: Build project
      - name: Build
        run: dotnet build ./WebApp/WebApp.sln --configuration Release --no-restore

      # Step 5: Publish project
      - name: Publish
        run: dotnet publish ./WebApp/WebApp.sln --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Step 6: Deployment
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.TESTAPPPROD }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
